import {useState} from 'react';
import {Coins,Flame,Flower2,Apple,BookHeart,PanelTop,Wind,Settings,Check,Undo2,Archive,Trash2,Move,Plus,Sun,Moon,Sunset,RefreshCw,X} from 'lucide-react';
import {Panel,Toggle} from '../../components/Panel.jsx';
import {ITEMS,MAX_ITEMS,ASSET_ROOT} from './catalog.js';
export const fmtTime=ms=>{const t=Math.ceil(ms/1000);return`${Math.floor(t/60).toString().padStart(2,'0')}:${(t%60).toString().padStart(2,'0')}`};
const date=t=>new Date(t).toLocaleDateString('zh-CN');
const image=kind=>`${import.meta.env.BASE_URL}${ASSET_ROOT}${ITEMS[kind].file}`;
export function CaiyuanDock({panel,setPanel,view,api,onQuiet}){return <>{[
 ['incense','上香',Flame],['lamps','供灯',Flower2],['offerings','供品',Apple],['coin','投铜钱',Coins],['wishes','心愿',BookHeart],['quiet','静心',Wind],['layout','布置',PanelTop],['settings','设置',Settings]
 ].map(([id,name,Icon])=><button key={id} className={panel===(id==='settings'?id:'caiyuan-'+id)||(id==='layout'&&view?.tool==='arrange')||(id==='coin'&&view?.tool==='coin')?'active':''} onClick={()=>{if(id==='coin'){setPanel(null);api()?.command('tool','coin')}else if(id==='quiet'){api()?.clear();onQuiet()}else setPanel(id==='settings'?id:'caiyuan-'+id)}}><Icon/><span>{name}</span></button>)}</>}
export function CaiyuanSelection({view,api,setPanel}){if(!view?.tool)return null;const label=view.tool.startsWith('place:')?`放置${ITEMS[view.tool.slice(6)]?.name}`:({coin:'投铜钱 · 轻点供桌空处（最多三枚）',arrange:'布置中 · 长按摆件拖动',incense:'轻点香炉上香',lamp:'轻点莲灯开关',tea:'轻点茶杯添茶'})[view.tool];return <div className="caiyuan-selection"><span>{label}</span>{view.selectedId&&view.tool==='arrange'&&<button onClick={()=>setPanel('caiyuan-object')}>调整所选摆件</button>}<button disabled={!view.canUndo} aria-label="撤销摆设" onClick={()=>api()?.command('undo')}><Undo2 size={15}/></button><button aria-label="结束当前操作" onClick={()=>api()?.clear()}><X size={15}/></button></div>}
export function CaiyuanEnvironment({view,api}){return <div className="caiyuan-settings"><p className="caiyuan-eyebrow">阁内生趣</p><Toggle label="招财小金蟾" description="眨眨眼，走走停停，帮你把铜钱送进聚宝盆。" checked={view?.settings.showToad??true} onChange={showToad=>api()?.command('settings',{showToad})}/><Toggle label="薄云与浮尘" description="云气留在桌前，侧光里浮着几粒微尘。" checked={view?.settings.showAtmosphere??true} onChange={showAtmosphere=>api()?.command('settings',{showAtmosphere})}/><Toggle label="减少阁内动态" description="环境放慢，金蟾以待机和眨眼为主；主动投币仍会回应。" checked={view?.settings.reduceMotion??false} onChange={reduceMotion=>api()?.command('settings',{reduceMotion})}/><p className="caiyuan-eyebrow">阁内光阴</p><div className="caiyuan-time">{[['auto','跟随时间',RefreshCw],['day','白天',Sun],['dusk','傍晚',Sunset],['night','夜晚',Moon]].map(([id,name,Icon])=><button key={id} aria-pressed={view?.settings.time===id} onClick={()=>api()?.command('settings',{time:id})}><Icon size={17}/>{name}</button>)}</div><Toggle label="背景音乐 · 阁内清音" description="几声弦音，低声循环陪伴。" checked={view?.settings.music??true} onChange={music=>api()?.command('settings',{music})}/>{(view?.settings.music??true)&&<label className="range-row"><span>配乐音量 <b>{Math.round((view?.settings.musicVolume??.45)*100)}%</b></span><input aria-label="财源广进配乐音量" type="range" min="0" max="1" step=".05" value={view?.settings.musicVolume??.45} onChange={e=>api()?.command('settings',{musicVolume:Number(e.target.value)})}/></label>}<Toggle label="互动音效" description="摆放轻响、添一杯温茶。" checked={view?.settings.effects??true} onChange={effects=>api()?.command('settings',{effects})}/><div className="caiyuan-sound-preview"><button className="text-button" onClick={()=>api()?.previewSound('tea')}>试听添茶</button><button className="text-button" onClick={()=>api()?.previewSound('lamp')}>试听轻响</button></div>{view?.audioStatus==='error'&&<p className="inline-note">有一段声音暂未载入，请重新进入此主题。</p>}<label className="range-row"><span>本主题音量 <b>{Math.round((view?.settings.volume??.65)*100)}%</b></span><input aria-label="财源广进音量" type="range" min="0" max="1" step=".05" value={view?.settings.volume??.65} onChange={e=>api()?.command('settings',{volume:Number(e.target.value)})}/></label></div>}
function ItemControls({item,api,onClose}){if(!item)return <p className="inline-note">先轻点一个供桌摆件。</p>;return <div className="caiyuan-item-controls"><img src={image(item.kind)} alt={ITEMS[item.kind].name}/><label className="range-row"><span>摆件大小 <b>{Math.round(item.scale*100)}%</b></span><input aria-label="摆件大小" type="range" min={ITEMS[item.kind].min} max={ITEMS[item.kind].max} step=".05" value={item.scale} onChange={e=>api()?.command('scale',{id:item.id,scale:Number(e.target.value)})}/></label><div className="caiyuan-buttons"><button className="text-button" onClick={()=>{api()?.command(item.stored?'restore':'store',item.id);onClose()}}><Archive size={16}/>{item.stored?'摆回供桌':'收纳'}</button><button className="text-button" onClick={()=>{api()?.command('remove',item.id);onClose()}}><Trash2 size={16}/>移除</button></div><p className="inline-note">长按桌上的摆件即可拖动，松手自动保存。收纳和移除都可在布置中撤销。收起香炉会熄灭本次燃香。</p></div>}
function WishNote({view,api,onClose}){
 const [edit,setEdit]=useState(()=>view.wishes.find(w=>w.id===view.activeWishId)||view.wishes[0]||null);
 const [content,setContent]=useState(()=>edit?.content||''),[showHistory,setShowHistory]=useState(false);
 function load(w){setEdit(w);setContent(w?.content||'');setShowHistory(false)}
 function save(e){
  e.preventDefault();
  const result=api()?.command('wishSave',{id:edit?.id,content});
  if(result?.ok)onClose();
 }
 return <div className="caiyuan-wish-note">
  <form className="caiyuan-wish-editor" onSubmit={save}>
   <label>我的心愿<textarea aria-label="心愿内容" value={content} maxLength={120} rows={4} placeholder="愿努力有收获，愿家人常平安。" onChange={e=>setContent([...e.target.value].slice(0,60).join(''))}/></label>
   <small className="caiyuan-counter">{[...content].length} / 60 字</small>
   <div className="caiyuan-buttons">
    <button type="submit" className="primary-button" disabled={!content.trim()}><Check size={16}/>保存到祈愿牌</button>
    {edit&&<button type="button" className="text-button" onClick={()=>load(null)}><Plus size={15}/>写新心愿</button>}
   </div>
  </form>
  {view.wishes.length>0&&<div className="caiyuan-wish-history">
   <button className="text-button" aria-expanded={showHistory} onClick={()=>setShowHistory(!showHistory)}>写过的心愿 · {view.wishes.length}</button>
   {showHistory&&<div className="caiyuan-wish-list">{view.wishes.map(w=><button className={edit?.id===w.id?'selected':''} key={w.id} onClick={()=>load(w)}><strong>{w.content}</strong><small>{date(w.createdAt)}{view.activeWishId===w.id?' · 牌上心愿':''}</small></button>)}</div>}
  </div>}
 </div>
}
export function CaiyuanPanels({panel,view,api,onClose,setPanel}){
 if(!view||!panel?.startsWith('caiyuan-'))return null;const name=panel.slice(8),selected=view.items.find(i=>i.id===view.selectedId),burner=view.items.find(i=>i.kind==='burner'&&!i.stored),inc=view.incense,minutes=view.settings.duration;
 const cmd=(a,p)=>api()?.command(a,p);const tool=(type)=>{cmd('tool',type);onClose()};
 const titles={incense:['三炷清香，片刻从容','点燃前，先为自己留一点安静的时间。'],lamps:['留一盏，温柔的光','每一盏莲灯，都可以独自亮着。'],offerings:['一桌心意，随手摆好','选好一件，再轻点供桌放下。'],wishes:['把心愿，写给好日子','简单写几句，留在祈愿牌上。'],layout:['供桌之间，自有心意','长按摆件自由拖动，也可以添加、缩放或收纳。'],object:[selected?ITEMS[selected.kind].name:'供桌摆件','摆件的位置与大小，随你的心意。'],time:['日月流转，灯火常温','光阴可以跟随电脑，也可以停留在此刻。']};const [title,subtitle]=titles[name]||titles.layout;
 return <Panel wide={name==='layout'} title={title} subtitle={subtitle} onClose={onClose}><div className="caiyuan-panel">
 {name==='incense'&&<><div className="caiyuan-incense-summary"><img src={image('burner')} alt="香炉"/><div><strong>{!burner?'供桌上还没有香炉':inc.status==='burning'?'香正缓缓燃着':inc.status==='spent'?'这一炉香已燃尽':'三炷香，尚未点燃'}</strong><span>{inc.status==='burning'?`还余 ${fmtTime(inc.remaining)}`:'让心安静一会儿'}</span></div></div><div className="caiyuan-duration">{[3,10,20].map(m=><button key={m} aria-pressed={m===minutes} onClick={()=>cmd('settings',{duration:m})}>{m} 分钟</button>)}</div>{inc.status==='burning'?<div className="caiyuan-buttons"><button className="text-button" onClick={()=>cmd('extinguish',burner?.id)}>熄香</button><button className="primary-button" onClick={()=>cmd('ignite',{id:burner?.id,minutes,restart:true})}>重新上香</button></div>:<button className="primary-button" disabled={!burner} onClick={()=>tool('incense')}><Flame size={17}/>选好时间，轻点香炉</button>}<p className="inline-note">切换风景或关闭窗口，时间仍会自然流逝。无需守候，也没有离开惩罚。</p></>}
 {name==='lamps'&&<><div className="caiyuan-buttons"><button className="primary-button" onClick={()=>tool('lamp')}>轻点莲灯，单独开关</button><button className="text-button" onClick={()=>cmd('lamps',true)}>全部点亮</button><button className="text-button" onClick={()=>cmd('lamps',false)}>全部熄灭</button></div><div className="caiyuan-lamp-list">{view.items.filter(i=>i.kind==='lamp'&&!i.stored).map((i,n)=><button key={i.id} aria-pressed={i.lit} onClick={()=>cmd('lamp',i.id)}><img src={image('lamp')} alt=""/><span>莲灯 {n+1} · {i.lit?'已点亮':'已熄灭'}</span></button>)}</div><button className="text-button" onClick={()=>tool('place:lamp')}><Plus size={15}/>添一盏莲灯</button></>}
 {name==='offerings'&&<><div className="caiyuan-catalog">{['fruit','pastry','teapot','cup'].map(k=><button key={k} onClick={()=>tool('place:'+k)}><img src={image(k)} alt=""/><span>{ITEMS[k].name}</span></button>)}</div><button className="primary-button" onClick={()=>tool('tea')}>添茶 · 轻点一只茶杯</button><p className="inline-note">供品以整盘摆放。添茶前，请先把茶壶摆在桌上。</p></>}
 {name==='wishes'&&<WishNote view={view} api={api} onClose={onClose}/>}
 {name==='layout'&&<><div className="caiyuan-buttons"><button className="primary-button" onClick={()=>tool('arrange')}><Move size={16}/>进入布置 · 拖动摆件</button><button className="text-button" disabled={!view.canUndo} onClick={()=>cmd('undo')}><Undo2 size={16}/>撤销摆设</button></div><div className="caiyuan-catalog">{Object.entries(ITEMS).map(([k,v])=><button key={k} disabled={view.items.length>=MAX_ITEMS||(k==='burner'&&view.items.some(i=>i.kind===k))} onClick={()=>tool('place:'+k)}><img src={image(k)} alt=""/><span>添加{v.name}</span></button>)}</div><p className="caiyuan-eyebrow">桌上 {view.items.filter(i=>!i.stored).length} 件 · 收纳 {view.items.filter(i=>i.stored).length} 件 · 共 {view.items.length} / {MAX_ITEMS}</p><div className="caiyuan-items">{view.items.map(i=><div key={i.id}><button className="caiyuan-item-name" onClick={()=>{cmd('select',i.id);setPanel('caiyuan-object')}}><img src={image(i.kind)} alt=""/>{ITEMS[i.kind].name}<small>{i.stored?'已收纳':'桌上'}</small></button><button className="text-button" onClick={()=>cmd(i.stored?'restore':'store',i.id)}>{i.stored?'摆回':'收纳'}</button><button className="icon-button" aria-label={`移除${ITEMS[i.kind].name}`} onClick={()=>cmd('remove',i.id)}><Trash2 size={14}/></button></div>)}</div><div className="section-divider"/><div className="caiyuan-buttons"><button className="text-button" onClick={()=>cmd('reset')}><RefreshCw size={16}/>恢复默认摆设</button><button className="text-button" onClick={()=>cmd('clearTable')}><Archive size={16}/>收空供桌</button></div><p className="inline-note">恢复默认与收空都可撤销，只改变布局和道具状态，心愿记录会保留。</p></>}
 {name==='object'&&<ItemControls item={selected} api={api} onClose={onClose}/>}
 {name==='time'&&<CaiyuanEnvironment view={view} api={api}/>}
 </div></Panel>
}
