import test from 'node:test';import assert from 'node:assert/strict';
import {CaiyuanModel} from '../src/themes/caiyuan/model.js';import {CaiyuanLife} from '../src/themes/caiyuan/toad.js';import {freePoint,pathTo,clearSegment,safePoints,distance} from '../src/themes/caiyuan/habitat.js';import {lanternPose} from '../src/themes/caiyuan/life-renderer.js';
const run=(l,seconds,options={})=>{for(let i=0;i<seconds*60;i++)l.update(1/60,options)};
const setup=()=>{const m=new CaiyuanModel();m.state.settings.time='day';return {m,l:new CaiyuanLife(m,()=>.5)}};
test('motion upgrade retains old objects/settings/wishes and adds the bowl once',()=>{const base=setup().m.snapshot();delete base.motion;base.items=base.items.filter(i=>i.kind!=='bowl');base.items[1].x=.31;base.settings.volume=.2;base.wishes=[{id:'mine',content:'我的心愿',progress:[]}];const m=new CaiyuanModel(base);assert.deepEqual(m.state.items.slice(0,9),base.items);assert.equal(m.state.settings.volume,.2);assert.equal(m.state.wishes[0].content,'我的心愿');assert.equal(m.state.items.filter(i=>i.kind==='bowl').length,1);m.command('store',m.state.items.at(-1).id);const restored=new CaiyuanModel(m.snapshot());assert.equal(restored.state.items.filter(i=>i.kind==='bowl').length,1);assert.equal(restored.state.items.at(-1).stored,true)});
test('pre-motion intentionally empty and full tables are not overwritten',()=>{for(const items of [[],Array.from({length:24},(_,i)=>({id:'c'+i,kind:'cup',x:.03+i*.04,y:.85,scale:1}))]){const m=new CaiyuanModel({initialized:true,items});assert.equal(m.state.items.length,items.length);assert.equal(m.state.motion.version,1)}});
test('paths clear every inflated prop footprint and short hops stay on table',()=>{const {m,l}=setup();for(const p of safePoints(m.state.items).filter((_,i)=>i%37===0)){const path=pathTo(l.position,p,m.state.items);if(!path)continue;let a=l.position;for(const b of path){assert.ok(clearSegment(a,b,m.state.items));a=b}}assert.equal(pathTo(l.position,{x:.5,y:.3},m.state.items),null);});
test('30 seconds idle includes blinking and autonomous hops; reduced motion stays put',()=>{const {l}=setup(),p={...l.position};run(l,30);assert.ok(l.hops>0);assert.ok(l.blinks>=3);assert.ok(distance(l.position,p)>20);const quiet=setup().l,start={...quiet.position};run(quiet,45,{reducedMotion:true});assert.equal(quiet.hops,0);assert.deepEqual(quiet.position,start);assert.ok(quiet.blinks>0)});
test('one coin has exactly one complete pickup, carry and delivery, never crosses obstacles',()=>{const {m,l}=setup();assert.ok(l.drop({x:.424,y:.886}).ok);let airborne=false,carried=false;for(let i=0;i<1500;i++){l.update(1/60);assert.ok(freePoint(l.position,m.state.items));airborne ||= l.height>4;carried ||= l.coins.some(c=>c.status==='carried');}assert.ok(airborne&&carried);assert.equal(l.delivered,1);assert.equal(l.coins.length,0);assert.ok(l.traces.some(t=>t.phase==='deliver'));run(l,30);assert.equal(l.delivered,1)});
test('three-coin limit and invalid drop do not destroy existing coins',()=>{const {l}=setup();assert.equal(l.drop({x:.5,y:.2}).ok,false);for(const x of [.386,.405,.424])assert.ok(l.drop({x,y:.886}).ok);assert.equal(l.drop({x:.44,y:.806}).ok,false);assert.equal(l.coins.length,3)});
test('missing bowl resolves held coin without waiting forever',()=>{const {m,l}=setup();m.state.items=m.state.items.filter(i=>i.kind!=='bowl');l.layoutChanged();l.drop({x:.424,y:.886});run(l,20);assert.equal(l.dissolved,1);assert.equal(l.coins.length,0);assert.equal(l.phase,'idle')});
test('moving or storing the bowl mid-task recomputes a safe route and resolves once',()=>{for(const action of ['move','store']){const {m,l}=setup(),b=m.state.items.find(i=>i.kind==='bowl');l.drop({x:.424,y:.886});run(l,5);const r=m.command(action,action==='store'?b.id:{id:b.id,x:.28,y:.804});assert.ok(r.ok);l.onAction(action);run(l,30);assert.equal(l.delivered+l.dissolved,1);assert.equal(l.coins.length,0);assert.ok(freePoint(l.position,m.state.items))}});
test('arrangement pauses picking up coins; edits are reconciled before resuming',()=>{const {m,l}=setup();l.drop({x:.424,y:.886});m.command('tool','arrange');const p={...l.position};run(l,35);assert.deepEqual(l.position,p);assert.equal(l.delivered,0);assert.equal(l.coins[0].status,'ground');m.command('cancel');run(l,25);assert.equal(l.delivered,1)});
test('large resume delta is clamped; safe feet/settings restore with no transient task',()=>{const {m,l}=setup();l.drop({x:.424,y:.886});run(l,2);const start={...l.position};l.update(900);assert.ok(distance(start,l.position)<5);m.command('settings',{showLanterns:false,showToad:false,showAtmosphere:false,ambient:false,motionIntensity:'gentle',reduceMotion:true});const restored=new CaiyuanModel(m.snapshot()),other=new CaiyuanLife(restored);assert.equal(other.phase,'idle');assert.equal(other.coins.length,0);assert.equal(restored.state.settings.showToad,false);assert.equal(restored.state.settings.showLanterns,true);assert.equal(restored.state.settings.ambient,true);assert.equal(restored.state.settings.motionIntensity,'standard');assert.equal(restored.state.settings.showAtmosphere,false);assert.equal(restored.state.settings.reduceMotion,true);assert.ok(freePoint(other.position,restored.state.items))});
test('lanterns differ, kicks capped and naturally decay',()=>{const {l}=setup();assert.notEqual(lanternPose(0,2,l).angle,lanternPose(1,2,l).angle);for(let n=0;n<100;n++)l.kickLantern(0);let maximum=0;for(let t=0;t<8;t+=.1){l.time=t;maximum=Math.max(maximum,Math.abs(lanternPose(0,t,l).angle))}assert.ok(maximum<.08);l.time=10;assert.equal(lanternPose(0,10,l).angle,lanternPose(0,10,null).angle)});
test('layout changes covering the toad move it to a safe place; no available table hides it safely',()=>{const {m,l}=setup();m.command('move',{id:m.state.items[0].id,...l.position});l.layoutChanged();assert.ok(freePoint(l.position,m.state.items));m.state.items=Array.from({length:24},(_,i)=>({id:'big'+i,kind:'fruit',scale:1.4,x:.04+(i%12)*.083,y:i<12?.82:.874}));l.layoutChanged();assert.equal(l.visible,false);run(l,20);assert.equal(l.hops,0)});
test('completed wish and incense reactions are short; rare events do not pile up',()=>{const {l,m}=setup();l.onAction('ignite');assert.equal(l.phase,'attention');run(l,3);assert.equal(l.phase,'idle');l.onAction('wishComplete');run(l,2);assert.equal(l.hops,1);assert.ok(l.glows.length<=1);l.nextEvent=l.time; l.lastInteraction=l.time;run(l,5);assert.notEqual(l.phase,'sleep');l.lastInteraction=l.time-30;l.nextEvent=l.time;run(l,1);assert.ok(l.goal?.kind==='visit'||l.phase==='attention');assert.ok(l.nextEvent-l.time>=118);assert.ok(l.glows.length<=1);});
test('bowl arrival prefers a visible torso instead of hiding behind the burner',async()=>{const {approach,occlusion}=await import('../src/themes/caiyuan/habitat.js');const {m,l}=setup(),b=m.state.items.find(i=>i.kind==='bowl'),target=approach(b,l.position,m.state.items);assert.ok(target);assert.ok(occlusion(target.p,m.state.items)<=1)});
test('night settles into longer pauses between autonomous outings',()=>{const {m,l}=setup();l.settle();const day=l.nextMove-l.time;m.state.settings.time='night';l.settle();assert.ok(l.nextMove-l.time>day*1.7)});
test('a click during a hop waits for landing, responds once, then completes its coin task',()=>{const {l}=setup();l.drop({x:.424,y:.886});run(l,1.8);assert.equal(l.phase,'hop');l.click();assert.equal(l.phase,'hop');run(l,.9);assert.equal(l.phase,'response');assert.equal(l.height,0);run(l,30);assert.equal(l.delivered,1);assert.equal(l.coins.length,0)});

test('blink state cannot interrupt takeoff, airborne posture or landing',()=>{
 const {l}=setup();l.phase='hop';l.blinkAt=l.time;l.doubleBlink=true;
 for(const height of [0,.4,1,9,18,9,.4,0]){l.height=height;assert.equal(l.pose(),height>.7?'hop':'idle')}
 l.phase='idle';assert.equal(l.pose(),'blink','quiet blinking remains available');
 l.phase='hop';l.height=9;l.coins=[{status:'carried'}];assert.equal(l.pose(),'carry','a carried coin stays in its arms throughout a hop');
});
