import test from 'node:test';
import assert from 'node:assert/strict';
const api=await import('../src/themes/caiyuan/model.js').catch(()=>({}));
const geo=await import('../src/themes/caiyuan/geometry.js').catch(()=>({}));
const now=new Date(2026,9,1,12).getTime();
test('caiyuan provides an isolated runnable state model',()=>assert.equal(typeof api.CaiyuanModel,'function'));
function model(saved){assert.equal(typeof api.CaiyuanModel,'function');return new api.CaiyuanModel(saved,now)}
test('first entry has nine offerings plus a treasure bowl, lit lamps and unlit incense',()=>{const m=model();assert.equal(m.state.initialized,true);assert.equal(m.state.items.length,10);assert.equal(m.state.items.filter(i=>i.kind==='lamp'&&i.lit).length,2);assert.equal(m.incense(now).status,'unlit');for(const i of m.state.items)assert.ok(geo.validPlacement(i));});
test('an explicitly emptied table stays empty on restart',()=>{const m=model();m.command('clearTable',null,now);assert.equal(model(m.snapshot()).state.items.length,0)});
test('incense uses timestamps and expires offline without events',()=>{const m=model(),b=m.state.items.find(i=>i.kind==='burner');m.command('ignite',{id:b.id,minutes:3},now);assert.equal(m.incense(now+90000).progress,.5);const restored=new api.CaiyuanModel(m.snapshot(),now+181000);assert.equal(restored.incense(now+181000).status,'spent');assert.equal(restored.events.length,0);assert.ok(m.incense(now-10000).progress>=0);});
test('incense is unique and storing it stops its burn',()=>{const m=model(),b=m.state.items.find(i=>i.kind==='burner');assert.equal(m.command('add',{kind:'burner',x:.5,y:.83},now).ok,false);m.command('ignite',{id:b.id,minutes:10},now);m.command('store',b.id,now+1000);assert.equal(m.incense(now+1000).status,'unlit')});
test('layout undo and reset preserve the wish book and legacy archive',()=>{const m=model({favorites:[2]});m.command('wishSave',{content:'认真完成一件小事',action:'今天先做十分钟'},now);const book=structuredClone(m.state.wishes),fav=[...m.state.favorites];m.command('clearTable',null,now);m.command('undo',null,now);assert.equal(m.state.items.length,10);m.command('reset',null,now);assert.deepEqual(m.state.wishes,book);assert.deepEqual(m.state.favorites,fav)});
test('out of table moves are rejected, scale has safe bounds',()=>{const m=model(),b=m.state.items[0],before={...b};assert.equal(m.command('move',{id:b.id,x:.5,y:.3},now).ok,false);assert.equal(b.y,before.y);m.command('scale',{id:b.id,scale:200},now);assert.ok(m.state.items[0].scale<=1.45)});
test('wish text is bounded, completion and progress survive restoration',()=>{const m=model();m.command('wishSave',{content:'心'.repeat(80),action:'一步一步来'},now);const w=m.state.wishes[0];assert.equal([...w.content].length,60);m.command('wishProgress',{id:w.id,text:'开始了'},now);m.command('wishComplete',w.id,now+1000);m.command('wishArchive',w.id,now+2000);const r=new api.CaiyuanModel(m.snapshot(),now+3000).state.wishes[0];assert.equal(r.progress.length,1);assert.equal(r.completedAt,now+1000);assert.equal(r.archived,true)});
test('content-only wish editing preserves legacy details and does not duplicate records',()=>{
 const m=model();const {id}=m.command('wishSave',{content:'旧心愿',action:'已经记录的小事'},now);
 m.command('wishProgress',{id,text:'旧进展'},now+1);m.command('wishComplete',id,now+2);m.command('wishArchive',id,now+3);
 const before=structuredClone(m.state.wishes[0]);assert.equal(m.command('wishSave',{id,content:'愿家人平安'},now+4).ok,true);
 const restored=new api.CaiyuanModel(m.snapshot(),now+6);assert.equal(restored.state.wishes.length,1);assert.deepEqual(restored.state.wishes[0],{...before,content:'愿家人平安'});assert.equal(restored.state.activeWishId,id);
 const saved=restored.snapshot();assert.equal(restored.command('wishSave',{id,content:'   '},now+5).ok,false);assert.deepEqual(restored.snapshot(),saved);
});
test('malformed save is repaired locally and population capped',()=>{const m=model({initialized:true,items:[{kind:'hacked'},null],wishes:null,settings:{volume:Infinity}});assert.equal(m.state.items.length,0);assert.ok(Number.isFinite(m.state.settings.volume));const fresh=model();for(let i=0;i<40;i++)fresh.command('add',{kind:'cup',x:.3+i*.005,y:.86},now);assert.equal(fresh.state.items.length,24)});
test('incense completion emits only once',()=>{const m=model(),b=m.state.items[0];m.command('ignite',{id:b.id,minutes:3},now);m.tick(now+180001);m.tick(now+180002);assert.equal(m.events.filter(e=>e==='complete').length,1)});
test('contain projection round-trips the same item at 16:9, 16:10 and ultrawide',()=>{assert.equal(typeof geo.sceneTransform,'function');for(const [w,h] of [[1600,900],[1440,900],[2560,1080],[700,900]]){const t=geo.sceneTransform(w,h),p={x:.53,y:.84},screen=geo.toScreen(p,t),world=geo.toWorld(screen,t);assert.ok(Math.abs(world.x-p.x)<1e-9);assert.ok(Math.abs(world.y-p.y)<1e-9);assert.ok(t.x>=0&&t.y>=0);assert.ok(t.width<=w+.001&&t.height<=h+.001)}});
test('valid placements survive restart without snapping to another point',()=>{const m=model();const r=m.command('add',{kind:'cup',x:.031,y:.872},now);assert.equal(r.ok,true);const saved=m.snapshot();assert.deepEqual(new api.CaiyuanModel(saved,now+1000).state.items,saved.items)});
test('scaling emits one undo step per continuous slider gesture',()=>{const m=model(),id=m.state.items[0].id;for(let n=0;n<6;n++)m.command('scale',{id,scale:1+n*.05},now+n*40);m.command('undo',null,now+300);assert.equal(m.state.items[0].scale,1)});
test('undo affects arrangement, not subsequent incense, lamp or tea actions',()=>{const m=model(),[b,l]=m.state.items,cup=m.state.items.find(i=>i.kind==='cup');m.command('move',{id:cup.id,x:.86,y:.87},now);m.command('ignite',{id:b.id,minutes:10},now+1000);m.command('lamp',l.id,now+1000);m.command('tea',cup.id,now+1000);m.command('undo',null,now+2000);assert.equal(m.incense(now+2000).status,'burning');assert.equal(m.state.items.find(i=>i.id===l.id).lit,false);assert.equal(m.state.items.find(i=>i.id===cup.id).tea,1)});
test('undo cannot relight incense extinguished or ended by storing/removing its burner',()=>{for(const action of ['extinguish','store','remove']){const m=model(),b=m.state.items[0];m.command('ignite',{id:b.id,minutes:10},now);if(action==='extinguish')m.command('move',{id:b.id,x:.52,y:.868},now+100);m.command(action,b.id,now+1000);m.command('undo',null,now+2000);assert.equal(m.incense(now+2000).status,'unlit',action)}});
test('the last drawn item at the same depth is also the first hit',async()=>{const {CaiyuanRenderer}=await import('../src/themes/caiyuan/renderer.js'),items=[{id:'under',kind:'cup',x:.5,y:.85,scale:1},{id:'over',kind:'cup',x:.5,y:.85,scale:1}],b=geo.bounds(items[0]);assert.equal(CaiyuanRenderer.prototype.hit.call({t:{width:1600},alpha:{}},{x:b.x+b.w*.5,y:b.y+b.h*.5},items)?.id,'over')});

test('removed blessing feature never redraws or mutates legacy records',()=>{const legacy={daily:{date:'2026-09-30',index:2},blessingHistory:{'2026-09-30':2},favorites:[2,7]};const m=model(legacy);const saved=m.snapshot();m.tick(now+86400000);assert.deepEqual(m.state.daily,legacy.daily);assert.deepEqual(m.state.blessingHistory,legacy.blessingHistory);assert.equal(m.command('blessing',null,now).ok,false);assert.equal(m.command('favorite',2,now).ok,false);const restored=new api.CaiyuanModel(saved,now+86400000).snapshot();assert.deepEqual(restored.favorites,legacy.favorites);assert.deepEqual(restored.items,saved.items)});
