// Browser plugin not available in this session. Uses the project's existing Playwright + Electron.
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),out=path.resolve(process.env.CAIYUAN_QA_OUTPUT||path.join(root,'test-results/caiyuan'));
const url=process.env.CAIYUAN_QA_URL||'http://127.0.0.1:5188/';
const {_electron}=require(root+'/node_modules/@playwright/test'),electron=require(root+'/node_modules/electron');
const report={checks:[],errors:[],screenshots:[],viewports:[]};
function observe(){window.sceneRuntime=selector=>{const node=document.querySelector(selector);if(!node)return null;let f=node[Object.keys(node).find(k=>k.startsWith('__reactFiber$'))];for(let i=0;f&&i<30;f=f.return,i++)for(let h=f.memoizedState,j=0;h&&j<30;h=h.next,j++){const r=h.memoizedState?.current;if((r?.game&&r?.renderer)||(r?.sim&&r?.canvas))return r}return null};window.cyRuntime=()=>{const node=document.querySelector('.caiyuan-stage');if(!node)return null;let f=node[Object.keys(node).find(k=>k.startsWith('__reactFiber$'))];for(let i=0;f&&i<30;f=f.return,i++)for(let h=f.memoizedState,j=0;h&&j<30;h=h.next,j++){const r=h.memoizedState?.current;if(r?.model&&r?.renderer)return r;}return null};}
(async()=>{fs.mkdirSync(out,{recursive:true});const profile=fs.mkdtempSync('/tmp/caiyuan-qa-');let app,page;
const capture=async(name)=>{await page.waitForTimeout(650);fs.writeFileSync(path.join(out,name+'.png'),Buffer.from(await app.evaluate(async({BrowserWindow})=>(await BrowserWindow.getAllWindows()[0].webContents.capturePage()).toPNG().toString('base64')),'base64'));report.screenshots.push(name)};
const boot=async()=>{app=await _electron.launch({executablePath:electron,args:[root,'--user-data-dir='+profile],env:{...process.env,VITE_DEV_SERVER_URL:url}});page=await app.firstWindow();page.setDefaultTimeout(20000);page.on('pageerror',e=>report.errors.push(e.message));await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];w.setContentSize(1600,1000);w.show()});await page.waitForSelector('.pond-canvas');await page.evaluate(observe)};
const state=()=>page.evaluate(()=>cyRuntime()?.model.view());
const close=async()=>{if(await page.getByRole('button',{name:'关闭面板',exact:true}).count())await page.getByRole('button',{name:'关闭面板',exact:true}).click()};
const dock=async name=>{await close();await page.getByRole('navigation',{name:'财源广进工具栏'}).getByRole('button',{name,exact:true}).click()};
const clickWorld=async(x,y)=>{const p=await page.evaluate(({x,y})=>{const r=cyRuntime(),t=r.renderer.t,b=r.renderer.canvas.getBoundingClientRect();return{x:b.x+t.x+x*t.width,y:b.y+t.y+y*t.height}},{x,y});await page.mouse.click(p.x,p.y);return p};
const clickItem=async(kind,n=0)=>{const p=await page.evaluate(async({kind,n})=>{const r=cyRuntime(),i=r.model.state.items.filter(i=>i.kind===kind&&!i.stored)[n],{bounds}=await import('/src/themes/caiyuan/geometry.js');const b=bounds(i),t=r.renderer.t;return{x:t.x+(b.x+b.w*.5)*t.width,y:t.y+(b.y+b.h*.57)*t.height}},{kind,n});await page.mouse.click(p.x,p.y);};
try{
await boot();await page.evaluate(()=>{localStorage.setItem('fusheng-settings',JSON.stringify({sound:false,volume:.18,season:'spring',weather:'sunny',day:'day',fishCount:12,quality:'high'}))});
await page.getByRole('button',{name:'切换主题',exact:true}).click();await page.locator('.theme-card').filter({has:page.getByText('财源广进',{exact:true})}).click();await page.waitForSelector('.caiyuan-canvas');await page.waitForFunction(()=>cyRuntime()?.renderer.stats().loaded>=11);await page.waitForTimeout(1200);let s=await state();assert.equal(s.items.length,10);assert.equal(s.incense.status,'unlit');assert.equal(s.items.filter(i=>i.kind==='lamp'&&i.lit).length,2);assert.equal(await page.locator('vite-error-overlay').count(),0);report.checks.push('first entry: nine original assets plus one treasure bowl, two lit lamps, unlit incense');await capture('01-default-table');
await dock('上香');await page.getByRole('button',{name:'3 分钟',exact:true}).click();await page.getByRole('button',{name:'选好时间，轻点香炉',exact:true}).click();await clickItem('burner');assert.equal((await state()).incense.status,'burning');assert.equal((await state()).items.find(i=>i.kind==='burner').incense.duration,180000);await page.keyboard.press('Escape');await clickItem('burner');await page.getByRole('button',{name:'熄香',exact:true}).click();assert.equal((await state()).incense.status,'unlit');await close();report.checks.push('incense duration selection, scene ignition, direct remaining-time panel, extinguish');
await dock('供灯');await page.getByRole('button',{name:'全部熄灭',exact:true}).click();assert.equal((await state()).items.filter(i=>i.kind==='lamp'&&i.lit).length,0);await close();await clickItem('lamp');assert.equal((await state()).items.filter(i=>i.kind==='lamp'&&i.lit).length,1);await dock('供灯');await page.getByRole('button',{name:'全部点亮',exact:true}).click();await close();report.checks.push('individual and all-lamp switches');
await dock('布置');await page.getByRole('button',{name:'添加茶杯',exact:true}).click();await clickWorld(.56,.88);assert.equal((await state()).items.length,11);await page.keyboard.press('Escape');await dock('布置');await page.getByRole('button',{name:'进入布置 · 拖动摆件',exact:true}).click();
const drag=await page.evaluate(async()=>{const r=cyRuntime(),i=r.model.state.items.find(i=>i.kind==='fruit'),{bounds}=await import('/src/themes/caiyuan/geometry.js'),b=bounds(i),t=r.renderer.t;return{id:i.id,x:t.x+(b.x+b.w*.5)*t.width,y:t.y+(b.y+b.h*.55)*t.height,dx:t.width*.055,old:i.x}});await page.mouse.move(drag.x,drag.y);await page.mouse.down();await page.mouse.move(drag.x+drag.dx,drag.y,{steps:20});await page.mouse.up();assert.ok((await state()).items.find(i=>i.id===drag.id).x>drag.old+.04);await capture('02-free-layout');await page.getByRole('button',{name:'调整所选摆件',exact:true}).click();const slider=page.getByRole('slider',{name:'摆件大小'});await slider.fill('0.85');await page.waitForTimeout(450);assert.equal((await state()).items.find(i=>i.id===drag.id).scale,.85);await page.getByRole('button',{name:'收纳',exact:true}).click();assert.equal((await state()).items.find(i=>i.id===drag.id).stored,true);await dock('布置');await page.getByRole('button',{name:'摆回',exact:true}).click();assert.equal((await state()).items.find(i=>i.id===drag.id).stored,false);await close();await page.keyboard.press('Escape');report.checks.push('add, drag, scale, store, restore');
await dock('供品');await page.getByRole('button',{name:'添茶 · 轻点一只茶杯',exact:true}).click();await clickItem('cup');assert.equal((await state()).items.filter(i=>i.kind==='cup')[0].tea,1);await page.keyboard.press('Escape');report.checks.push('teapot/cup tea interaction');
await dock('心愿');assert.equal(await page.getByRole('textbox').count(),1);await page.getByRole('textbox',{name:'心愿内容',exact:true}).fill('愿认真做的小事，慢慢开花。愿家人平安，日子温暖。');await capture('03-wish-editor');await page.getByRole('button',{name:'保存到祈愿牌',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});assert.equal((await state()).wishes.length,1);assert.equal((await state()).wishes[0].content,'愿认真做的小事，慢慢开花。愿家人平安，日子温暖。');
report.checks.push('single wish field, save closes panel and updates plaque');assert.equal(await page.getByRole('button',{name:'祝福笺',exact:true}).count(),0);
await dock('设置');await page.getByRole('button',{name:'夜晚',exact:true}).click();await close();await dock('上香');await page.getByRole('button',{name:'选好时间，轻点香炉',exact:true}).click();await clickItem('burner');await page.keyboard.press('Escape');await page.waitForTimeout(2300);await capture('04-night');
await dock('静心');await page.getByRole('button',{name:'退出沉浸模式',exact:true}).waitFor();assert.equal(await page.locator('.caiyuan-selection').count(),0);await page.keyboard.press('Escape');await page.getByRole('navigation',{name:'财源广进工具栏'}).waitFor({state:'visible'});report.checks.push('night light transition and quiet mode Escape exit');
const saved=await state();await app.close();await boot();await page.waitForSelector('.caiyuan-canvas');await page.waitForFunction(()=>cyRuntime()?.renderer.stats().loaded>=11);s=await state();assert.deepEqual(s.wishes,saved.wishes);assert.deepEqual(s.favorites,saved.favorites);assert.deepEqual(s.daily,saved.daily);assert.equal(s.settings.time,'night');assert.equal(s.items.find(i=>i.kind==='burner').incense.startedAt,saved.items.find(i=>i.kind==='burner').incense.startedAt);report.checks.push('process restart retains layout, wishes, legacy archive and incense start');
await dock('心愿');assert.equal(await page.locator('.caiyuan-wish-list').count(),0);await page.getByRole('button',{name:'写过的心愿 · 1',exact:true}).click();assert.ok(await page.locator('.caiyuan-wish-list').getByText('愿认真做的小事，慢慢开花。愿家人平安，日子温暖。',{exact:true}).isVisible());await close();
await dock('布置');await page.getByRole('button',{name:'收空供桌',exact:true}).click();assert.equal((await state()).items.length,0);await close();await page.reload();await page.waitForSelector('.caiyuan-canvas');await page.evaluate(observe);assert.equal((await state()).items.length,0);await dock('布置');await page.getByRole('button',{name:'恢复默认摆设',exact:true}).click();s=await state();assert.equal(s.items.length,10);assert.equal(s.wishes.length,1);assert.equal(s.favorites.length,0);await close();report.checks.push('wish history + clear/reload stays empty + restore defaults keeps wishes/legacy favorites');
for(const [w,h] of [[1600,900],[1440,900],[2560,1080],[1045,899]]){await app.evaluate(({BrowserWindow},{w,h})=>BrowserWindow.getAllWindows()[0].setContentSize(w,h),{w,h});await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].focus());await page.waitForTimeout(800);const before=(await state()).items.filter(i=>i.kind==='lamp')[0].lit;await clickItem('lamp');const st=await state();assert.equal(st.items.filter(i=>i.kind==='lamp')[0].lit,!before,JSON.stringify({w,h,debug:await page.evaluate(async()=>{const r=cyRuntime(),i=r.model.state.items.find(i=>i.kind==='lamp'),{bounds}=await import('/src/themes/caiyuan/geometry.js'),b=bounds(i),t=r.renderer.t,p={x:t.x+(b.x+b.w*.5)*t.width,y:t.y+(b.y+b.h*.57)*t.height};return{transform:t,tool:r.model.tool,hit:r.renderer.hit(r.renderer.world(p.x,p.y),r.model.state.items)?.id,element:document.elementFromPoint(p.x,p.y)?.outerHTML?.slice(0,150),point:p,hidden:document.hidden}})}));const t=await page.evaluate(()=>cyRuntime().renderer.t);assert.ok(t.x>=0&&t.y>=0&&t.width<=w+.01&&t.height<=h+.01);report.viewports.push({requested:{w,h},actual:await page.evaluate(()=>({w:innerWidth,h:innerHeight})),transform:t});if(w===2560)await capture('05-ultrawide');}
await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setContentSize(1600,1000));const original=await page.evaluate(()=>Object.fromEntries(Object.entries(localStorage).filter(([k])=>k==='fusheng-settings'||k==='fusheng-fish')));let cySave=await page.evaluate(()=>localStorage.getItem('mofish-caiyuan-v1'));await page.evaluate(()=>window.oldCyRuntime=cyRuntime());
for(const [id,name,canvas] of [['koi','锦鲤池','.pond-canvas'],['coast','赶海','.coast-canvas'],['cats','猫咪庭院','.cat-canvas'],['caiyuan','财源广进','.caiyuan-canvas']]){await page.getByRole('button',{name:'切换主题',exact:true}).click();await page.locator('.theme-card').filter({has:page.getByText(name,{exact:true})}).click();await page.waitForSelector('.theme-'+id+' '+canvas);await page.waitForTimeout(1000);assert.equal(await page.locator('vite-error-overlay').count(),0);if(id==='koi'){
 assert.equal(await page.evaluate(()=>oldCyRuntime.renderer.dead),true);
 await page.getByRole('button',{name:'投食',exact:true}).click();
 assert.ok(await page.evaluate(()=>sceneRuntime('.pond-canvas').sim.food.length>0));
 report.checks.push('koi feed button creates reachable pond food');
}if(id==='coast'){
 await page.waitForFunction(()=>sceneRuntime('.coast-canvas')?.renderer.sprites.size>=17);
 await page.getByRole('button',{name:'观察模式，点击切换捕捉',exact:true}).click();
 const target=await page.evaluate(()=>{const r=sceneRuntime('.coast-canvas');for(const e of r.game.entities.filter(e=>e.state==='scene'&&['crab','sandcrab','hermit','crab_rock','crab_pale','starfish','octopus'].includes(e.species)&&!e.concealment)){const p=r.renderer.worldToScreen(e.x,e.y);for(const d of [0,5,-5,10,-10]){const q={x:p.x+d,y:p.y};if(document.elementFromPoint(q.x,q.y)===r.renderer.canvas&&r.renderer.hitTest(q.x,q.y,r.game)?.id===e.id)return{...q,id:e.id}}}return {missing:true,entities:r.game.entities.map(e=>({species:e.species,state:e.state,x:e.x,y:e.y,concealment:e.concealment,submerged:e.submerged})),ready:r.renderer.sprites.size}});
 assert.ok(!target.missing,JSON.stringify(target));
 await page.mouse.click(target.x,target.y);await page.waitForFunction(id=>sceneRuntime('.coast-canvas').game.entities.some(e=>e.id===id&&e.state==='bucket'),target.id);
 await page.getByRole('button',{name:/^小桶/}).click();assert.ok(await page.locator('.bucket-row').count());await close();
 report.checks.push('coast catch cursor, actual crab capture and bucket panel');
}if(id==='cats'){
 await page.waitForFunction(()=>sceneRuntime('.cat-canvas')?.renderer.bounds.size>0);
 const cat=await page.evaluate(()=>{const r=sceneRuntime('.cat-canvas');for(const c of r.game.cats.filter(c=>c.active)){const b=r.renderer.bounds.get(c.id);if(!b)continue;const p={x:b.x+b.w*.5,y:b.y+b.h*.6};if(document.elementFromPoint(p.x,p.y)===r.renderer.canvas)return{...p,id:c.id,interactions:c.interactions}}return null});
 assert.ok(cat);await page.mouse.click(cat.x,cat.y);await page.waitForFunction(id=>sceneRuntime('.cat-canvas').game.cats.find(c=>c.id===id)?.task?.tool==='pet',cat.id);await page.waitForFunction(({id,interactions})=>sceneRuntime('.cat-canvas').game.cats.find(c=>c.id===id)?.interactions>interactions,cat);
 report.checks.push('cat direct pet gesture, designated cat response and completed interaction');
 await page.getByRole('button',{name:'猫咪',exact:true}).click();assert.ok(await page.getByRole('button',{name:'添加猫咪',exact:true}).isVisible());await close()}report.checks.push('theme '+id+' loaded');}
assert.deepEqual(await page.evaluate(()=>Object.fromEntries(Object.entries(localStorage).filter(([k])=>k==='fusheng-settings'||k==='fusheng-fish'))),original);assert.deepEqual(JSON.parse(await page.evaluate(()=>localStorage.getItem('mofish-caiyuan-v1'))),JSON.parse(cySave));report.checks.push('caiyuan renderer destroyed after leaving, old settings unchanged, new state restored');
assert.deepEqual(report.errors,[]);report.result='PASS';console.log(JSON.stringify(report,null,2));
}catch(e){report.result='FAIL';report.failure=e.stack;console.error(e);if(page){console.log(await page.locator('body').innerText().catch(()=>''));await Promise.race([capture('failure').catch(()=>{}),new Promise(resolve=>setTimeout(resolve,4000))])}process.exitCode=1}finally{fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));if(app){const child=app.process();let timer;await Promise.race([app.close().catch(()=>{}),new Promise(resolve=>{timer=setTimeout(()=>{child.kill();resolve()},5000)})]);clearTimeout(timer)}fs.rmSync(profile,{recursive:true,force:true})}
})()
