import {useState,useRef,useEffect} from 'react';
import {Sun,Cloud,CloudRain,CloudSnow,CloudFog,CloudLightning,LocateFixed,Search,RefreshCw,Check,MapPin} from 'lucide-react';
import {searchCities,lookupApproximateCity} from '../lib/environment.js';
import {Panel} from './Panel.jsx';
export const WEATHER={sunny:{name:'晴天',Icon:Sun},cloudy:{name:'多云',Icon:Cloud},rainy:{name:'细雨',Icon:CloudRain},snowy:{name:'落雪',Icon:CloudSnow},stormy:{name:'雷雨',Icon:CloudLightning},foggy:{name:'薄雾',Icon:CloudFog}};
export default function WeatherPanel({env,mode,onChange,onClose,notify}){
 const [query,setQuery]=useState(''),[results,setResults]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('');const req=useRef(null);
 useEffect(()=>()=>req.current?.abort(),[]);
 async function search(e){e.preventDefault();req.current?.abort();const ctrl=new AbortController();req.current=ctrl;setBusy(true);setError('');try{const list=await searchCities(query.trim(),{signal:ctrl.signal});if(!ctrl.signal.aborted){setResults(list);if(!list.length)setError('没有找到这个城市，试试英文或拼音。')}}catch(err){if(!ctrl.signal.aborted)setError('城市查询暂不可用，请稍后重试。')}finally{if(!ctrl.signal.aborted)setBusy(false)}}
 async function locate(){if(window.pondDesktop){setBusy(true);setError('');try{const c=await lookupApproximateCity();env.setCity(c);notify('已按网络位置更新城市，可随时手动更换')}catch{setError('网络定位暂不可用，请搜索城市。')}finally{setBusy(false)}return}if(!navigator.geolocation){setError('当前环境不支持定位，可搜索城市。');return}setBusy(true);setError('');navigator.geolocation.getCurrentPosition(p=>{env.setCity({id:'located',name:'当前位置',latitude:p.coords.latitude,longitude:p.coords.longitude});setBusy(false);notify('已使用你的位置更新天气')},()=>{setBusy(false);setError('未取得定位权限，可搜索城市或稍后重试。')},{timeout:10000,maximumAge:600000})}
 return <Panel title="把窗外，带进池塘" subtitle="天气每 15 分钟更新，也可以随心选一种心情。" onClose={onClose}><div className="weather-current"><div><MapPin size={16}/><strong>{env.city.name}</strong><span>{env.data?`${Math.round(env.data.temperature)}°`: '—°'}</span></div><button className="icon-button" aria-label="刷新天气" onClick={env.refresh} disabled={env.status==='loading'}><RefreshCw size={17} className={env.status==='loading'?'spin':''}/></button></div><p className="weather-source">{env.status==='live'?`已更新 · ${new Date(env.data.updatedAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}`:env.status==='loading'?'正在读取实时天气…':env.status==='cached'?'网络暂不可用 · 显示上次天气':'天气暂不可用 · 池塘使用默认晴天'}</p>{env.locationStatus==='approximate'&&<p className="inline-note">城市来自网络大致位置，可搜索修正。</p>}{env.locationStatus==='fallback'&&<p className="inline-note">自动定位暂不可用，先以武汉为默认城市。</p>}<form onSubmit={search} className="city-search"><Search size={17}/><input aria-label="搜索城市" placeholder="搜索城市，如武汉、杭州" value={query} onChange={e=>setQuery(e.target.value)}/><button type="submit" disabled={busy||query.trim().length<2}>查找</button></form>{error&&<p role="status" className="inline-note">{error}</p>}{results.length>0&&<div className="city-results">{results.map((c,i)=><button key={c.id||i} onClick={()=>{env.setCity(c);setResults([]);setQuery('');notify(`天气城市已切换为${c.name}`)}}><span>{c.name}<small>{c.country}</small></span><MapPin size={15}/></button>)}</div>}<button className="text-button locate" onClick={locate} disabled={busy}><LocateFixed size={15}/>{busy?'正在查询…':window.pondDesktop?'按网络定位城市':'使用我的位置'}</button><div className="section-divider"/><button className={`auto-choice ${mode==='auto'?'selected':''}`} onClick={()=>onChange('auto')}><span><RefreshCw size={17}/>跟随真实天气</span>{mode==='auto'&&<Check size={17}/>}</button><div className="weather-choices">{Object.entries(WEATHER).filter(([key])=>key!=='foggy').map(([key,{name,Icon}])=><button aria-pressed={mode===key} key={key} className={mode===key?'selected':''} onClick={()=>onChange(key)}><Icon size={23}/><span>{name}</span></button>)}</div><p className="attribution">天气数据来自 <a href="https://open-meteo.com/" target="_blank" rel="noreferrer">Open-Meteo</a> · 城市搜索 GeoNames</p></Panel>
}
