import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {Fish,Leaf,Cloud,Moon,Sun,Monitor,Settings,Maximize,Minimize,Check,RefreshCw,Minus,EyeOff,X} from 'lucide-react';
import Pond from './components/Pond.jsx';
import {Panel} from './components/Panel.jsx';
import WeatherPanel,{WEATHER} from './components/WeatherPanel.jsx';
import SeasonPanel,{SEASONS} from './components/SeasonPanel.jsx';
import SettingsPanel from './components/SettingsPanel.jsx';
import KoiStudio from './components/KoiStudio.jsx';
import {loadSettings,loadFish,writeStore} from './lib/storage.js';
import {useEnvironment} from './hooks/useEnvironment.js';
import {useAmbient} from './hooks/useAmbient.js';
function FeedIcon(){return <svg width="25" height="25" viewBox="0 0 28 28" fill="none" stroke="currentColor" strokeWidth="1.4"><circle cx="14" cy="6.5" r="4"/><circle cx="7" cy="20" r="4"/><circle cx="22" cy="20" r="4"/></svg>}
export default function App(){
 const [settings,setSettings]=useState(()=>{const s=loadSettings();try {if(!localStorage.getItem('fusheng-settings'))s.reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;} catch {}return s}),[fish,setFish]=useState(loadFish),[panel,setPanel]=useState(null),[immersive,setImmersive]=useState(false),[paused,setPaused]=useState(false),[toast,setToast]=useState(''),[desktop,setDesktop]=useState(null),[windowBusy,setWindowBusy]=useState(false);const pond=useRef(null),timer=useRef(null);
 const env=useEnvironment(settings);const ambient=useAmbient(settings.sound,settings.volume,env.weather,env.season,env.night);
 const notify=useCallback(text=>{setToast(text);clearTimeout(timer.current);timer.current=setTimeout(()=>setToast(''),3300)},[]);
 const update=useCallback((key,value)=>setSettings(s=>({...s,[key]:value})),[]);const closePanel=useCallback(()=>setPanel(null),[]);
 useEffect(()=>{if(!writeStore('fusheng-settings',settings))notify('存储空间不足，当前设置仅保留到本次关闭。')},[settings,notify]);
 useEffect(()=>()=>clearTimeout(timer.current),[]);
 useEffect(()=>{const bridge=window.pondDesktop;if(!bridge)return;let lastMode=false,active=true;const receive=state=>{if(!active)return;setDesktop(state);if(state.desktopMode!==lastMode){lastMode=state.desktopMode;if(state.desktopMode)setPanel(null);setImmersive(state.desktopMode)}};bridge.getState().then(receive);const off=bridge.onState(receive);return()=>{active=false;off()}},[]);
 useEffect(()=>{function onKey(e){if(e.key!=='Escape'&&e.target.closest('input,textarea,select,button,a,[role="button"],[contenteditable="true"]'))return;if(e.key==='Escape'){if(panel)setPanel(null);else if(immersive)setImmersive(false)}if(e.code==='Space'&&!panel){e.preventDefault();pond.current?.feed();notify('一把鱼食，一池欢喜')}if(e.key.toLowerCase()==='h'&&!panel)setImmersive(v=>!v)}window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[panel,immersive,notify]);
 const options=useMemo(()=>({season:env.season,weather:env.weather,night:env.night,paused,desktopMode:!!desktop?.desktopMode,reducedMotion:settings.reducedMotion,fishCount:settings.fishCount,fishSize:settings.fishSize,turtleCount:settings.turtleCount,quality:settings.quality,solarTerm:env.solarTerm,onThunder:ambient.thunder}),[env.season,env.weather,env.night,paused,settings.reducedMotion,settings.fishCount,settings.fishSize,settings.turtleCount,settings.quality,env.solarTerm,desktop?.desktopMode,ambient.thunder]);
 function saveFish(f){const next=[...fish,f];if(!writeStore('fusheng-fish',next)){notify('存储空间不足，未能保存这尾锦鲤。');return}setFish(next);setPanel(null);notify(`${f.name}已游入池塘，下次见面它还在。`)}
 function removeFish(id){const next=fish.filter(f=>f.id!==id);if(writeStore('fusheng-fish',next)){setFish(next);notify('锦鲤已从池塘移走')}}
 function resizeFish(id,size){const next=fish.map(f=>f.id===id?{...f,size}:f);if(writeStore('fusheng-fish',next))setFish(next);else notify('存储空间不足，未能保存大小。')}
 async function desktopAction(action,value){setWindowBusy(true);try{const result=await window.pondDesktop[action](value);if(result){setDesktop(result);if(action==='setDesktopMode'&&result.message)notify(result.message)}}catch{notify('窗口操作未完成，请从菜单栏重试。')}finally{setWindowBusy(false)}}
 const getStats=useCallback(()=>pond.current?.stats(),[]);
 const WeatherIcon=WEATHER[env.weather]?.Icon||Sun;const hidden=immersive||desktop?.desktopMode;
 return <main className={`app season-${env.season} ${env.night?'night':'day'} weather-${env.weather} ${hidden?'immersive':''} ${desktop?'native-app':''}`}>
  {ambient.tracks.map(track=><audio key={track.id} data-ambient={track.id} ref={track.ref} src={track.url} loop={track.loop} preload="none" hidden aria-hidden="true"/>)}<div className="pond-background"/><div className="scene-light"/><Pond ref={pond} options={options} fish={fish} desktop={desktop}/><div className="edge-shade"/>
  <div className="hud"><header className="topbar"><div className="brand"><span className="brand-symbol"><Fish size={34} strokeWidth={1.5}/></span><div><h1>浮生</h1><span>锦 鲤 池</span></div></div><button className="weather-badge" onClick={()=>setPanel('weather')} aria-label="打开天气设置"><WeatherIcon size={23}/><span>{env.city.name}</span><strong>{env.data?`${Math.round(env.data.temperature)}°`:'—°'}</strong><span className="weather-label">{settings.weather==='auto'?(env.status==='live'?env.data.description:env.status==='loading'?'获取中':env.status==='cached'?'缓存':'离线'):WEATHER[env.weather].name}</span></button></header>
  <div className="poem"><span className="poem-line"/><p>一池清欢</p><span className="poem-line"/><small>把日子，慢慢游成诗。</small></div>
  <div className="scene-status"><p>{SEASONS[env.season].label}<i/> {env.night?'夜色':'白昼'} <span className="solar-term">· {env.solarTerm}</span></p><span>{fish.length+settings.fishCount} 尾锦鲤 {settings.turtleCount>0&&`· ${settings.turtleCount} 只小乌龟`} {paused&&'· 静止片刻'}</span></div>
  <div className="dock-wrap"><p className="feed-hint"><span/>轻点水面，投下一份小小欢喜<span/></p><nav className="dock" aria-label="池塘工具栏"><button onClick={()=>{pond.current?.feed();notify('一把鱼食，一池欢喜')}}><FeedIcon/><span>投食</span></button><button className={panel==='season'?'active':''} onClick={()=>setPanel(panel==='season'?null:'season')}><Leaf/><span>四时</span></button><button className={panel==='weather'?'active':''} onClick={()=>setPanel(panel==='weather'?null:'weather')}><Cloud/><span>天气</span></button><button className={panel==='day'?'active':''} onClick={()=>setPanel(panel==='day'?null:'day')}>{env.night?<Sun/>:<Moon/>}<span>日夜</span></button><button className={panel==='studio'?'active':''} onClick={()=>setPanel('studio')}><Fish/><span>画锦鲤</span></button><button className={panel==='settings'?'active':''} onClick={()=>setPanel(panel==='settings'?null:'settings')}><Settings/><span>设置</span></button></nav></div>
  <div className="scene-actions"><button className="desktop-button" disabled={windowBusy} aria-label="桌面模式" title={desktop?.desktopSupported?'进入桌面模式 · ⌘ ⇧ K 恢复控制':'桌面模式'} onClick={()=>desktop?.desktopSupported?desktopAction('setDesktopMode',true):setPanel('desktop')}><Monitor/><span>桌面</span></button><button className="immersive-button" onClick={()=>{setImmersive(true);notify('已收起界面 · 按 Esc 或右下角按钮返回')}}><Maximize size={18}/><span>沉浸</span></button></div></div>
  {desktop&&!desktop.desktopMode&&<div className="window-bar"><div className="window-drag" title="拖动这里移动窗口；拖动窗口边缘调整大小"/><div className="window-actions" role="group" aria-label="窗口控制"><button disabled={windowBusy} aria-label={desktop.fullScreen?'退出全屏':'窗口全屏'} title={desktop.fullScreen?'退出全屏':'全屏'} onClick={()=>desktopAction('setFullScreen',!desktop.fullScreen)}>{desktop.fullScreen?<Minimize size={15}/>:<Maximize size={15}/>}</button><button aria-label="最小化窗口" title="最小化" onClick={()=>desktopAction('minimize')}><Minus size={16}/></button><button aria-label="隐藏窗口" title="隐藏 · 菜单栏锦鲤图标或 ⌘ ⇧ K 恢复" onClick={()=>desktopAction('hide')}><EyeOff size={16}/></button><button className="window-close" aria-label="关闭程序" title="关闭程序" onClick={()=>desktopAction('quit')}><X size={17}/></button></div></div>}
  {hidden&&!desktop?.desktopMode&&<button className="restore-button" aria-label="退出沉浸模式" onClick={()=>setImmersive(false)}><Minimize size={19}/></button>}
  {toast&&<div className="toast" role="status"><Check size={16}/>{toast}</div>}
  {panel==='weather'&&<WeatherPanel env={env} mode={settings.weather} onChange={v=>update('weather',v)} onClose={closePanel} notify={notify}/>}
  {panel==='desktop'&&<Panel title="让池塘，住进桌面" subtitle="轻轻流动，陪你做自己的事。" onClose={closePanel}><div className="desktop-notice"><Monitor size={25}/><div><strong>{desktop?'当前系统暂不支持桌面池塘':'请打开「浮生锦鲤池」桌面应用'}</strong><p>{desktop?'可以先在这里收起界面，静静观鱼。':'在桌面应用首页点「桌面」，池塘就会铺在桌面图标下方，鼠标操作照常。浏览器内可以先体验沉浸观鱼。'}</p></div></div><p className="shortcut-note">桌面应用中按 ⌘ ⇧ K，或点菜单栏锦鲤图标，可随时恢复控制。</p><button className="primary-button" onClick={()=>{setPanel(null);setImmersive(true)}}><Maximize size={18}/>先体验沉浸模式</button></Panel>}
  {panel==='season'&&<SeasonPanel mode={settings.season} current={env.season} solarTerm={env.solarTerm} onChange={v=>update('season',v)} onClose={closePanel}/>}
  {panel==='day'&&<Panel title="日升月落，各有温柔" subtitle="白日有蝶，入夜有萤。" onClose={closePanel}><div className="day-choices">{[{id:'auto',name:'跟随日夜',desc:'依据城市天气与本机时间',Icon:RefreshCw},{id:'day',name:'留住白昼',desc:'阳光轻落，蝴蝶翩跹',Icon:Sun},{id:'night',name:'一池星光',desc:'晚风徐徐，流萤点点',Icon:Moon}].map(({id,name,desc,Icon})=><button className={settings.day===id?'selected':''} key={id} onClick={()=>update('day',id)}><Icon size={25}/><span><strong>{name}</strong><small>{desc}</small></span>{settings.day===id&&<Check size={18}/>}</button>)}</div></Panel>}
  {panel==='studio'&&<KoiStudio onClose={closePanel} onSave={saveFish} fish={fish} onRemove={removeFish} onResize={resizeFish} turtleCount={settings.turtleCount} onTurtles={v=>update('turtleCount',v)}/>}
  {panel==='settings'&&<SettingsPanel soundStatus={ambient.status} soundDescription={ambient.description} getStats={getStats} settings={settings} update={update} paused={paused} setPaused={setPaused} desktop={desktop} onDesktop={v=>desktopAction('setDesktopMode',v)} onGlobal={v=>desktopAction('setGlobalInteraction',v)} onLogin={v=>desktopAction('setLaunchAtLogin',v)} onClose={closePanel} notify={notify}/>}
 </main>
}
